on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Build message packages
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --merge-install --packages-select \
            motion_msgs \
            ception_msgs \
            interaction_msgs \
            cascade_lifecycle_msgs \
            automation_msgs \
            cyberdog_interfaces
        shell: bash
